### ISSUE TITLE
Change font color if colour contrast is too little

### ISSUE THREAD

**Issue by MarcGoekce** [KraXen72/obsidian-painter#5]
If the highlight colour is black or something too dark, the text can't be read (easily).

| Preview | Source code |
|---|---|
| ![image](https://github.com/KraXen72/obsidian-painter/assets/161037915/a61b3b3d-1f04-4915-816b-3659fb37747a) | ![image](https://github.com/KraXen72/obsidian-painter/assets/161037915/9ba647de-008d-413a-9e50-f3b8fd027c4a)|

Instead of adding a secondary colour parameter, what if there is an option (or the default) that changes the font colour to white depending of the contrast?  

https://stackoverflow.com/questions/3942878/how-to-decide-font-color-in-white-or-black-depending-on-background-color

**Comment by KraXen72** [comment]
this is quite difficult to do. it would require me to either calculate the contrast, which i want to avoid doing because it'll make even more of the stylesheet generated, or use some [background-blend-mode](https://developer.mozilla.org/en-US/docs/Web/CSS/background-blend-mode) trickerly.   
I'm going to keep this issue open, but no promises or ETA.   
PR's are welcome as long as it does not decrease performance. (if you want to calculate the colors, i suggest using an external library for it)

**Comment by KraXen72** [comment]
i have decided to track this in #9
