### ISSUE TITLE
About a recall function similar to masking highlighted text in marginnote

### ISSUE THREAD

**Issue by 0xChrisJL** [KraXen72/obsidian-painter#6]
Hello, is it possible to be in reading mode Recall mode?
Similar to marginnote where you mask the highlighted text and clicking on the mask shows the text under the mask

If there is a plugin with similar functionality, please recommend it, thank you very much!

**Comment by KraXen72** [comment]
This is pretty niche, so i won't be implementing it into the main plugin.
However, you can add this with a custom css snippet.
pick one of [these styles](https://github.com/KraXen72/obsidian-painter/blob/master/styles.css) and add some css to make the `color` the same as `background-color` or vice-versa, so that they become unreadable. If you need help with creating this css snippet, there are many helpful people in the obsidian discord and i believe you'llget it working quickly.
